/**
 * String enums stored as TEXT columns (SQLite has no native enum; this keeps
 * the schema portable to PostgreSQL where they can become real enums later).
 */
export const EMPLOYMENT_TYPES = ['FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERN'] as const;
export type EmploymentType = (typeof EMPLOYMENT_TYPES)[number];

export const EMPLOYMENT_STATUSES = ['ACTIVE', 'INACTIVE', 'TERMINATED'] as const;
export type EmploymentStatus = (typeof EMPLOYMENT_STATUSES)[number];

/** Audit action codes. Convention: <VERB>_<ENTITY>. */
export const AUDIT_ACTIONS = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  ACTIVATE_USER: 'ACTIVATE_USER',
  DEACTIVATE_USER: 'DEACTIVATE_USER',
  UPDATE_USER_ROLES: 'UPDATE_USER_ROLES',
  RESET_USER_PASSWORD: 'RESET_USER_PASSWORD',
  UPDATE_ROLE_PERMISSIONS: 'UPDATE_ROLE_PERMISSIONS',
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
  ACTIVATE_ORGANIZATION: 'ACTIVATE_ORGANIZATION',
  DEACTIVATE_ORGANIZATION: 'DEACTIVATE_ORGANIZATION',
  CREATE_DEPARTMENT: 'CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
  ACTIVATE_DEPARTMENT: 'ACTIVATE_DEPARTMENT',
  DEACTIVATE_DEPARTMENT: 'DEACTIVATE_DEPARTMENT',
  CREATE_JOB: 'CREATE_JOB',
  UPDATE_JOB: 'UPDATE_JOB',
  ACTIVATE_JOB: 'ACTIVATE_JOB',
  DEACTIVATE_JOB: 'DEACTIVATE_JOB',
  CREATE_POSITION: 'CREATE_POSITION',
  UPDATE_POSITION: 'UPDATE_POSITION',
  ACTIVATE_POSITION: 'ACTIVATE_POSITION',
  DEACTIVATE_POSITION: 'DEACTIVATE_POSITION',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  ACTIVATE_EMPLOYEE: 'ACTIVATE_EMPLOYEE',
  DEACTIVATE_EMPLOYEE: 'DEACTIVATE_EMPLOYEE',
  CHANGE_EMPLOYEE_POSITION: 'CHANGE_EMPLOYEE_POSITION',
  CHANGE_EMPLOYEE_MANAGER: 'CHANGE_EMPLOYEE_MANAGER',
  UPDATE_DEPARTMENT_HEAD: 'UPDATE_DEPARTMENT_HEAD',
  UPDATE_SETTING: 'UPDATE_SETTING',
} as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
