/**
 * Permission codes — the single list used by BOTH backend (requirePermission)
 * and frontend (PermissionGuard / menu). Format: `<module>.<action>`.
 *
 * Adding a module in the future = add its codes here + seed them.
 */
export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',

  EMPLOYEES_VIEW: 'employees.view',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_UPDATE: 'employees.update',
  EMPLOYEES_ACTIVATE: 'employees.activate',

  ORGANIZATION_VIEW: 'organization.view',
  ORGANIZATION_MANAGE: 'organization.manage',

  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_ACTIVATE: 'users.activate',

  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',

  AUDIT_VIEW: 'audit.view',

  SETTINGS_MANAGE: 'settings.manage',

  WORKFLOW_APPROVE: 'workflow.approve',
  WORKFLOW_VIEW_ALL: 'workflow.view_all',
  WORKFLOW_MANAGE_DEFINITIONS: 'workflow.manage_definitions',

  CALENDAR_VIEW: 'calendar.view',
  CALENDAR_MANAGE: 'calendar.manage',
  LEAVE_MANAGE_TYPES: 'leave.manage_types',
  LEAVE_MANAGE_POLICIES: 'leave.manage_policies',
  LEAVE_MANAGE_ENTITLEMENTS: 'leave.manage_entitlements',
  LEAVE_VIEW: 'leave.view',
  LEAVE_REQUEST: 'leave.request',
  ONBOARDING_MANAGE: 'onboarding.manage',
  ACCOUNT_MANAGE_RECOVERY: 'account.manage_recovery',
  PRIVACY_MANAGE_REQUESTS: 'privacy.manage_requests',
  PRIVACY_EXPORT_DATA: 'privacy.export_data',

  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_CLOCK: 'attendance.clock',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_CORRECT: 'attendance.correct',
  ATTENDANCE_SCHEDULE_MANAGE: 'attendance.schedule_manage',

  OT_VIEW: 'ot.view',
  OT_REQUEST: 'ot.request',
  OT_MANAGE_POLICY: 'ot.manage_policy',

  PAYROLL_VIEW_OWN: 'payroll.view_own',
  PAYROLL_MANAGE: 'payroll.manage',
  PAYROLL_RUN: 'payroll.run',
  PAYROLL_APPROVE: 'payroll.approve',

  PERFORMANCE_VIEW: 'performance.view',
  PERFORMANCE_REVIEW: 'performance.review',
  PERFORMANCE_MANAGE_CYCLES: 'performance.manage_cycles',
  PERFORMANCE_MANAGE_KPIS: 'performance.manage_kpis',

  COMPETENCY_VIEW: 'competency.view',
  COMPETENCY_ASSESS: 'competency.assess',
  COMPETENCY_MANAGE: 'competency.manage',

  TRAINING_VIEW: 'training.view',
  TRAINING_MANAGE: 'training.manage',
  TRAINING_ENROLL: 'training.enroll',
  TRAINING_RECORD_RESULT: 'training.record_result',
  IDP_VIEW: 'idp.view',
  IDP_MANAGE: 'idp.manage',

  EMPLOYEE_RELATIONS_VIEW: 'employee_relations.view',
  EMPLOYEE_RELATIONS_MANAGE: 'employee_relations.manage',
  EMPLOYEE_RELATIONS_ISSUE: 'employee_relations.issue',
  EMPLOYEE_RELATIONS_ACKNOWLEDGE: 'employee_relations.acknowledge',

  RECRUITMENT_VIEW: 'recruitment.view',
  RECRUITMENT_MANAGE: 'recruitment.manage',
  RECRUITMENT_INTERVIEW: 'recruitment.interview',
  RECRUITMENT_MANAGE_OFFERS: 'recruitment.manage_offers',
  RECRUITMENT_HIRE: 'recruitment.hire',
  CAREER_VIEW: 'career.view',
  CAREER_MANAGE: 'career.manage',
  TALENT_VIEW: 'talent.view',
  TALENT_ASSESS: 'talent.assess',
  TALENT_MANAGE: 'talent.manage',
  TALENT_VIEW_REPORTS: 'talent.view_reports',
  SUCCESSION_VIEW: 'succession.view',
  SUCCESSION_MANAGE: 'succession.manage',
  EMPLOYEE360_VIEW: 'employee360.view',
  ANALYTICS_VIEW_EXECUTIVE: 'analytics.view_executive',
  ANALYTICS_VIEW_PAYROLL_AGGREGATE: 'analytics.view_payroll_aggregate',
  DOCUMENTS_VIEW_OWN: 'documents.view_own',
  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_MANAGE: 'documents.manage',
  REPORTS_VIEW: 'reports.view',
  REPORTS_VIEW_INDIVIDUAL: 'reports.view_individual',
  REPORTS_CREATE: 'reports.create',
  REPORTS_SHARE: 'reports.share',
  REPORTS_MANAGE: 'reports.manage',
  COPILOT_USE: 'copilot.use',
  WORKFORCE_VIEW: 'workforce.view',
  WORKFORCE_PLAN: 'workforce.plan',
  WORKFORCE_MANAGE: 'workforce.manage',
  ORG_DESIGN_VIEW: 'organization_design.view',
  ORG_DESIGN_MANAGE: 'organization_design.manage',
  ENGAGEMENT_RESPOND: 'engagement.respond',
  ENGAGEMENT_VIEW_RESULTS: 'engagement.view_results',
  ENGAGEMENT_MANAGE: 'engagement.manage',
  ONBOARDING_VIEW: 'onboarding.view',
  ONBOARDING_COMPLETE_TASKS: 'onboarding.complete_tasks',
  PROBATION_VIEW: 'probation.view',
  PROBATION_REVIEW: 'probation.review',
  PROBATION_MANAGE: 'probation.manage',
  OFFBOARDING_VIEW: 'offboarding.view',
  OFFBOARDING_MANAGE: 'offboarding.manage',
  OFFBOARDING_COMPLETE_TASKS: 'offboarding.complete_tasks',
  OFFBOARDING_COMPLETE_SEPARATION: 'offboarding.complete_separation',
  LIFECYCLE_VIEW_REPORTS: 'lifecycle.view_reports',
  OJT_VIEW: 'ojt.view',
  OJT_MANAGE: 'ojt.manage',
  OJT_TRAIN: 'ojt.train',
  OJT_ASSESS: 'ojt.assess',
  LEARNING_PATH_VIEW: 'learning_path.view',
  LEARNING_PATH_MANAGE: 'learning_path.manage',
  CERTIFICATION_VIEW: 'certification.view',
  CERTIFICATION_MANAGE: 'certification.manage',
  LEARNING_VIEW_REPORTS: 'learning.view_reports',

  // Benefits / welfare and claims (Task 36). Confidential by design: the manager TEAM scope never widens these.
  BENEFITS_VIEW_OWN: 'benefits.view_own',
  BENEFITS_VIEW: 'benefits.view',
  BENEFITS_MANAGE: 'benefits.manage',
  BENEFITS_CLAIM: 'benefits.claim',
  BENEFITS_REVIEW_CLAIMS: 'benefits.review_claims',
  BENEFITS_RECORD_PAYMENT: 'benefits.record_payment',
  BENEFITS_VIEW_REPORTS: 'benefits.view_reports',

  // Expense and travel (Task 39). Business expenditure, not welfare: separate tables, separate permissions. A manager's
  // TEAM scope never opens a subordinate's expenses; approvers see what they must decide, through the workflow.
  EXPENSE_VIEW_OWN: 'expense.view_own',
  EXPENSE_SUBMIT: 'expense.submit',
  EXPENSE_VIEW: 'expense.view',
  EXPENSE_MANAGE: 'expense.manage',
  EXPENSE_REVIEW: 'expense.review',
  EXPENSE_RECORD_PAYMENT: 'expense.record_payment',
  EXPENSE_VIEW_REPORTS: 'expense.view_reports',

  // Employee services (Task 40): service requests and HR letters. Fulfilling a ticket never grants source-domain
  // access: a salary-bearing letter needs the payroll authority as well.
  SERVICE_REQUEST_VIEW_OWN: 'service_request.view_own',
  SERVICE_REQUEST_CREATE: 'service_request.create',
  SERVICE_REQUEST_VIEW: 'service_request.view',
  SERVICE_REQUEST_FULFILL: 'service_request.fulfill',
  SERVICE_REQUEST_MANAGE: 'service_request.manage',
  HR_LETTER_VIEW_OWN: 'hr_letter.view_own',
  HR_LETTER_ISSUE: 'hr_letter.issue',
  HR_LETTER_MANAGE_TEMPLATES: 'hr_letter.manage_templates',
  HR_LETTER_VIEW_REPORTS: 'hr_letter.view_reports',
  // Compensation planning (Task 43) — a high-impact domain: humans decide, the system only calculates budget impact.
  COMP_PLAN_VIEW_TEAM: 'compensation_planning.view_team',
  COMP_PLAN_PLAN: 'compensation_planning.plan',
  COMP_PLAN_REVIEW: 'compensation_planning.review',
  COMP_PLAN_MANAGE_CYCLES: 'compensation_planning.manage_cycles',
  COMP_PLAN_MANAGE_BUDGET: 'compensation_planning.manage_budget',
  COMP_PLAN_FINALIZE: 'compensation_planning.finalize',
  COMP_PLAN_APPLY: 'compensation_planning.apply',
  COMP_PLAN_VIEW_REPORTS: 'compensation_planning.view_reports',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export interface PermissionDefinition {
  code: PermissionCode;
  module: string;
  description: string;
}

/** Seed source for the `permissions` table. */
export const PERMISSION_DEFINITIONS: PermissionDefinition[] = [
  { code: PERMISSIONS.DASHBOARD_VIEW, module: 'dashboard', description: 'View dashboard' },

  { code: PERMISSIONS.EMPLOYEES_VIEW, module: 'employees', description: 'View employees (scope depends on role data scope)' },
  { code: PERMISSIONS.EMPLOYEES_CREATE, module: 'employees', description: 'Create employees' },
  { code: PERMISSIONS.EMPLOYEES_UPDATE, module: 'employees', description: 'Edit employees' },
  { code: PERMISSIONS.EMPLOYEES_ACTIVATE, module: 'employees', description: 'Activate / inactivate employees' },

  { code: PERMISSIONS.ORGANIZATION_VIEW, module: 'organization', description: 'View organization structure' },
  { code: PERMISSIONS.ORGANIZATION_MANAGE, module: 'organization', description: 'Manage organizations, departments, jobs and positions' },

  { code: PERMISSIONS.USERS_VIEW, module: 'users', description: 'View user accounts' },
  { code: PERMISSIONS.USERS_CREATE, module: 'users', description: 'Create user accounts' },
  { code: PERMISSIONS.USERS_UPDATE, module: 'users', description: 'Edit user accounts and assign roles' },
  { code: PERMISSIONS.USERS_ACTIVATE, module: 'users', description: 'Activate / deactivate user accounts' },

  { code: PERMISSIONS.ROLES_VIEW, module: 'roles', description: 'View roles and permissions' },
  { code: PERMISSIONS.ROLES_MANAGE, module: 'roles', description: 'Change role ↔ permission mapping' },

  { code: PERMISSIONS.AUDIT_VIEW, module: 'audit', description: 'View audit logs' },

  { code: PERMISSIONS.SETTINGS_MANAGE, module: 'settings', description: 'Manage system settings' },

  { code: PERMISSIONS.WORKFLOW_APPROVE, module: 'workflow', description: 'Act on approval steps assigned to me' },
  { code: PERMISSIONS.WORKFLOW_VIEW_ALL, module: 'workflow', description: 'View every workflow instance' },
  { code: PERMISSIONS.WORKFLOW_MANAGE_DEFINITIONS, module: 'workflow', description: 'Create and activate workflow definition versions' },

  { code: PERMISSIONS.CALENDAR_VIEW, module: 'calendar', description: 'View work calendars and holidays' },
  { code: PERMISSIONS.CALENDAR_MANAGE, module: 'calendar', description: 'Manage work calendars, holidays and organization default calendar' },
  { code: PERMISSIONS.LEAVE_MANAGE_TYPES, module: 'leave', description: 'Manage leave types' },
  { code: PERMISSIONS.LEAVE_MANAGE_POLICIES, module: 'leave', description: 'Manage leave policies' },
  { code: PERMISSIONS.LEAVE_MANAGE_ENTITLEMENTS, module: 'leave', description: 'Generate and adjust leave entitlements, view ledgers' },
  { code: PERMISSIONS.LEAVE_VIEW, module: 'leave', description: 'View leave requests and balances within my data scope' },
  { code: PERMISSIONS.LEAVE_REQUEST, module: 'leave', description: 'Create, submit and cancel my own leave requests' },
  { code: PERMISSIONS.ONBOARDING_MANAGE, module: 'onboarding', description: 'Manage onboarding: templates, plans and task assignment, plus the customer data import workbook' },
  { code: PERMISSIONS.ACCOUNT_MANAGE_RECOVERY, module: 'account', description: 'Issue one-time password reset links and revoke other users\' sessions' },
  { code: PERMISSIONS.PRIVACY_MANAGE_REQUESTS, module: 'privacy', description: 'Record and track privacy requests from data subjects' },
  { code: PERMISSIONS.PRIVACY_EXPORT_DATA, module: 'privacy', description: 'Export an employee\'s personal data' },

  { code: PERMISSIONS.ATTENDANCE_VIEW, module: 'attendance', description: 'View attendance (scope depends on role data scope)' },
  { code: PERMISSIONS.ATTENDANCE_CLOCK, module: 'attendance', description: 'Clock in and out for yourself' },
  { code: PERMISSIONS.ATTENDANCE_MANAGE, module: 'attendance', description: 'Manage shifts and recalculate attendance' },
  { code: PERMISSIONS.ATTENDANCE_CORRECT, module: 'attendance', description: 'Decide attendance correction requests' },
  { code: PERMISSIONS.ATTENDANCE_SCHEDULE_MANAGE, module: 'attendance', description: 'Assign work schedules' },

  { code: PERMISSIONS.OT_VIEW, module: 'ot', description: 'View overtime requests (scope depends on role data scope)' },
  { code: PERMISSIONS.OT_REQUEST, module: 'ot', description: 'Claim overtime for yourself' },
  { code: PERMISSIONS.OT_MANAGE_POLICY, module: 'ot', description: 'Manage overtime policies' },

  { code: PERMISSIONS.PAYROLL_VIEW_OWN, module: 'payroll', description: 'View your own payslips' },
  { code: PERMISSIONS.PAYROLL_MANAGE, module: 'payroll', description: 'Manage compensation, pay components and payroll configuration' },
  { code: PERMISSIONS.PAYROLL_RUN, module: 'payroll', description: 'Calculate and close payroll runs' },
  { code: PERMISSIONS.PAYROLL_APPROVE, module: 'payroll', description: 'Decide payroll runs' },

  { code: PERMISSIONS.PERFORMANCE_VIEW, module: 'performance', description: 'View your own performance plan and aggregate performance reports' },
  { code: PERMISSIONS.PERFORMANCE_REVIEW, module: 'performance', description: 'Review the performance plans you are the assigned reviewer for' },
  { code: PERMISSIONS.PERFORMANCE_MANAGE_CYCLES, module: 'performance', description: 'Manage performance cycles and the plans inside them' },
  { code: PERMISSIONS.PERFORMANCE_MANAGE_KPIS, module: 'performance', description: 'Manage the KPI library' },

  { code: PERMISSIONS.COMPETENCY_VIEW, module: 'competency', description: 'View your own competency profile and aggregate competency reports' },
  { code: PERMISSIONS.COMPETENCY_ASSESS, module: 'competency', description: 'Assess the competency assessments you are the assigned reviewer for' },
  { code: PERMISSIONS.COMPETENCY_MANAGE, module: 'competency', description: 'Manage the competency framework, job profiles and assessment cycles' },

  { code: PERMISSIONS.TRAINING_VIEW, module: 'training', description: 'View the course catalogue and your own training record' },
  { code: PERMISSIONS.TRAINING_MANAGE, module: 'training', description: 'Manage training needs, courses and sessions' },
  { code: PERMISSIONS.TRAINING_ENROLL, module: 'training', description: 'Enrol employees on training sessions' },
  { code: PERMISSIONS.TRAINING_RECORD_RESULT, module: 'training', description: 'Record training attendance and results' },
  { code: PERMISSIONS.IDP_VIEW, module: 'training', description: 'View your own development plan' },
  { code: PERMISSIONS.IDP_MANAGE, module: 'training', description: 'Create and manage individual development plans' },

  { code: PERMISSIONS.EMPLOYEE_RELATIONS_VIEW, module: 'employee_relations', description: 'View employee relations cases and disciplinary history' },
  { code: PERMISSIONS.EMPLOYEE_RELATIONS_MANAGE, module: 'employee_relations', description: 'Manage employee relations cases, actions and configuration' },
  { code: PERMISSIONS.EMPLOYEE_RELATIONS_ISSUE, module: 'employee_relations', description: 'Submit disciplinary actions for approval and issue warning letters' },
  { code: PERMISSIONS.EMPLOYEE_RELATIONS_ACKNOWLEDGE, module: 'employee_relations', description: 'Acknowledge receipt of a disciplinary document issued to you' },

  { code: PERMISSIONS.RECRUITMENT_VIEW, module: 'recruitment', description: 'View the requisitions, openings and applications you are the hiring manager or an interviewer for' },
  { code: PERMISSIONS.RECRUITMENT_MANAGE, module: 'recruitment', description: 'Manage requisitions, openings, candidates, applications and interviews' },
  { code: PERMISSIONS.RECRUITMENT_INTERVIEW, module: 'recruitment', description: 'Give feedback on interviews you are assigned to' },
  { code: PERMISSIONS.RECRUITMENT_MANAGE_OFFERS, module: 'recruitment', description: 'Draft, submit and record the outcome of job offers, including compensation proposals' },
  { code: PERMISSIONS.RECRUITMENT_HIRE, module: 'recruitment', description: 'Convert an accepted candidate into an employee record' },
  { code: PERMISSIONS.CAREER_VIEW, module: 'talent', description: 'See own career paths, target job requirements and competency readiness' },
  { code: PERMISSIONS.CAREER_MANAGE, module: 'talent', description: 'Define career paths and job-to-job transitions' },
  { code: PERMISSIONS.TALENT_VIEW, module: 'talent', description: 'See talent review outcomes and talent pools within the data scope' },
  { code: PERMISSIONS.TALENT_ASSESS, module: 'talent', description: 'Submit a potential assessment as the assigned reviewer' },
  { code: PERMISSIONS.TALENT_MANAGE, module: 'talent', description: 'Run talent review cycles, configure buckets, manage talent pools and create development actions' },
  { code: PERMISSIONS.TALENT_VIEW_REPORTS, module: 'talent', description: 'Aggregate talent and succession reporting — counts only, never an individual' },
  { code: PERMISSIONS.SUCCESSION_VIEW, module: 'talent', description: 'See succession plans and nominated successors' },
  { code: PERMISSIONS.SUCCESSION_MANAGE, module: 'talent', description: 'Create succession plans, nominate successors and record readiness' },
  { code: PERMISSIONS.EMPLOYEE360_VIEW, module: 'analytics', description: 'Open the Employee 360 view; every section still needs its own source-module permission' },
  { code: PERMISSIONS.ANALYTICS_VIEW_EXECUTIVE, module: 'analytics', description: 'Executive HR dashboard — organization-level aggregates only, never an individual' },
  { code: PERMISSIONS.ANALYTICS_VIEW_PAYROLL_AGGREGATE, module: 'analytics', description: 'Organization-level payroll totals on the executive dashboard (gross, deductions, net, headcount paid)' },
  { code: PERMISSIONS.DOCUMENTS_VIEW_OWN, module: 'documents', description: 'See and download own documents whose classification allows the employee to see them' },
  { code: PERMISSIONS.DOCUMENTS_VIEW, module: 'documents', description: 'Browse the document center within the data scope; classification and the linked domain still apply' },
  { code: PERMISSIONS.DOCUMENTS_MANAGE, module: 'documents', description: 'Upload, version, link and archive documents and manage categories; required for RESTRICTED documents' },
  { code: PERMISSIONS.REPORTS_VIEW, module: 'reports', description: 'Open the report center and run reports on datasets the caller is otherwise authorized for' },
  { code: PERMISSIONS.REPORTS_VIEW_INDIVIDUAL, module: 'reports', description: 'Run datasets that return individual rows (not aggregate-only datasets); source-module scope still applies' },
  { code: PERMISSIONS.REPORTS_CREATE, module: 'reports', description: 'Save private report definitions' },
  { code: PERMISSIONS.REPORTS_SHARE, module: 'reports', description: 'Share saved reports with other report users (sharing never grants dataset access)' },
  { code: PERMISSIONS.REPORTS_MANAGE, module: 'reports', description: 'Edit or delete any saved report' },
  { code: PERMISSIONS.COPILOT_USE, module: 'copilot', description: 'Open the HR Copilot. Grants no data: every answer is built from tools that re-check the source module\'s permission and scope' },
  { code: PERMISSIONS.WORKFORCE_VIEW, module: 'workforce', description: 'See workforce planning cycles, headcount plans and vacancies within the data scope (aggregate figures)' },
  { code: PERMISSIONS.WORKFORCE_PLAN, module: 'workforce', description: 'Create planning cycles and edit planned headcount, reasons, priorities and planned movements' },
  { code: PERMISSIONS.WORKFORCE_MANAGE, module: 'workforce', description: 'Finalize and archive planning cycles and hand a planned demand to recruitment (with recruitment.manage)' },
  { code: PERMISSIONS.ORG_DESIGN_VIEW, module: 'workforce', description: 'See organization-design scenarios and their comparison with the current structure' },
  { code: PERMISSIONS.ORG_DESIGN_MANAGE, module: 'workforce', description: 'Create, edit, duplicate and finalize organization-design scenarios (never the live organization)' },
  { code: PERMISSIONS.ENGAGEMENT_RESPOND, module: 'engagement', description: 'Answer surveys assigned to me' },
  { code: PERMISSIONS.ENGAGEMENT_VIEW_RESULTS, module: 'engagement', description: 'See aggregate survey results within the data scope — never an individual answer' },
  { code: PERMISSIONS.ENGAGEMENT_MANAGE, module: 'engagement', description: 'Run surveys: question bank, audiences, open/close, participation, identified-survey respondent detail and closed anonymous comments' },
  { code: PERMISSIONS.ONBOARDING_VIEW, module: 'lifecycle', description: 'See onboarding plans and tasks within the data scope (own plan for an employee)' },
  { code: PERMISSIONS.ONBOARDING_COMPLETE_TASKS, module: 'lifecycle', description: 'Complete onboarding tasks assigned to me' },
  { code: PERMISSIONS.PROBATION_VIEW, module: 'lifecycle', description: 'See probation cases within the data scope (own dates and outcome for an employee)' },
  { code: PERMISSIONS.PROBATION_REVIEW, module: 'lifecycle', description: 'Submit the probation review I am assigned as reviewer' },
  { code: PERMISSIONS.PROBATION_MANAGE, module: 'lifecycle', description: 'Configure probation policies, open cases and reassign reviewers' },
  { code: PERMISSIONS.OFFBOARDING_VIEW, module: 'lifecycle', description: 'See offboarding cases within the data scope (own checklist for an employee)' },
  { code: PERMISSIONS.OFFBOARDING_MANAGE, module: 'lifecycle', description: 'Manage offboarding: templates, cases, tasks, dates, reason notes and exit interview notes' },
  { code: PERMISSIONS.OFFBOARDING_COMPLETE_TASKS, module: 'lifecycle', description: 'Complete offboarding tasks assigned to me' },
  { code: PERMISSIONS.OFFBOARDING_COMPLETE_SEPARATION, module: 'lifecycle', description: 'Complete an employment separation from a ready offboarding case (the one action that changes the employee master)' },
  { code: PERMISSIONS.LIFECYCLE_VIEW_REPORTS, module: 'lifecycle', description: 'Aggregate lifecycle reporting: joiners, onboarding completion, probation outcomes, departures — counts only' },
  { code: PERMISSIONS.OJT_VIEW, module: 'learning', description: 'See OJT plans within the data scope (own plans for an employee)' },
  { code: PERMISSIONS.OJT_MANAGE, module: 'learning', description: 'Define OJT programs, open plans, assign trainers, activate and complete plans, hand evidence to competency assessment' },
  { code: PERMISSIONS.OJT_TRAIN, module: 'learning', description: 'As the assigned trainer: record observations and trainer comments on assigned OJT plans only' },
  { code: PERMISSIONS.OJT_ASSESS, module: 'learning', description: 'Submit the final OJT assessment on plans assigned to me' },
  { code: PERMISSIONS.LEARNING_PATH_VIEW, module: 'learning', description: 'See learning paths and own assignments' },
  { code: PERMISSIONS.LEARNING_PATH_MANAGE, module: 'learning', description: 'Define learning paths and assign them to employees' },
  { code: PERMISSIONS.CERTIFICATION_VIEW, module: 'learning', description: 'See certification definitions and certifications within the data scope' },
  { code: PERMISSIONS.CERTIFICATION_MANAGE, module: 'learning', description: 'Define certifications; issue, renew and revoke employee certifications' },
  { code: PERMISSIONS.LEARNING_VIEW_REPORTS, module: 'learning', description: 'Aggregate learning reporting: training, OJT, learning path and certification counts' },
  { code: PERMISSIONS.BENEFITS_VIEW_OWN, module: 'benefits', description: 'See your own benefit enrolments, balances and claims' },
  { code: PERMISSIONS.BENEFITS_VIEW, module: 'benefits', description: 'Benefits administration view: plans, enrolments, entitlements and claims (organization-wide scope only; never widened by a team scope)' },
  { code: PERMISSIONS.BENEFITS_MANAGE, module: 'benefits', description: 'Configure categories, plans, eligibility, periods; enrol employees; generate and adjust entitlements' },
  { code: PERMISSIONS.BENEFITS_CLAIM, module: 'benefits', description: 'Create and submit your own benefit claims' },
  { code: PERMISSIONS.BENEFITS_REVIEW_CLAIMS, module: 'benefits', description: 'Open the review view of any claim, including confidential descriptions' },
  { code: PERMISSIONS.BENEFITS_RECORD_PAYMENT, module: 'benefits', description: 'Record that an approved claim was paid, or hand it to payroll (with the payroll permission)' },
  { code: PERMISSIONS.BENEFITS_VIEW_REPORTS, module: 'benefits', description: 'Aggregate benefits reporting: plan, enrolment, entitlement and claim totals; no person' },
  { code: PERMISSIONS.EXPENSE_VIEW_OWN, module: 'expense', description: 'See your own travel requests, expense reports and reimbursements' },
  { code: PERMISSIONS.EXPENSE_SUBMIT, module: 'expense', description: 'Create and submit your own travel requests and expense reports' },
  { code: PERMISSIONS.EXPENSE_VIEW, module: 'expense', description: 'Expense administration view: travel requests, expense reports and payments (organization-wide scope only; never widened by a team scope)' },
  { code: PERMISSIONS.EXPENSE_MANAGE, module: 'expense', description: 'Configure expense categories, expense and travel policies' },
  { code: PERMISSIONS.EXPENSE_REVIEW, module: 'expense', description: 'Open the review view of any travel request or expense report' },
  { code: PERMISSIONS.EXPENSE_RECORD_PAYMENT, module: 'expense', description: 'Record that an approved reimbursement was paid, or hand it to payroll (with the payroll permission)' },
  { code: PERMISSIONS.EXPENSE_VIEW_REPORTS, module: 'expense', description: 'Aggregate expense and travel reporting by policy, category and month; no person' },

  { code: PERMISSIONS.SERVICE_REQUEST_VIEW_OWN, module: 'employee_services', description: 'View your own service requests' },
  { code: PERMISSIONS.SERVICE_REQUEST_CREATE, module: 'employee_services', description: 'Create and submit your own service requests' },
  { code: PERMISSIONS.SERVICE_REQUEST_VIEW, module: 'employee_services', description: 'View the service request queue, submitted values and internal notes' },
  { code: PERMISSIONS.SERVICE_REQUEST_FULFILL, module: 'employee_services', description: 'Assign, answer, fulfil and reject service requests' },
  { code: PERMISSIONS.SERVICE_REQUEST_MANAGE, module: 'employee_services', description: 'Manage the service catalogue and request form fields' },
  { code: PERMISSIONS.HR_LETTER_VIEW_OWN, module: 'employee_services', description: 'View your own issued HR letters' },
  { code: PERMISSIONS.HR_LETTER_ISSUE, module: 'employee_services', description: 'Issue and void HR letters (a salary letter also needs the payroll authority)' },
  { code: PERMISSIONS.HR_LETTER_MANAGE_TEMPLATES, module: 'employee_services', description: 'Manage HR letter templates' },
  { code: PERMISSIONS.HR_LETTER_VIEW_REPORTS, module: 'employee_services', description: 'Aggregate service request and HR letter reporting; no person' },
  { code: PERMISSIONS.COMP_PLAN_VIEW_TEAM, module: 'compensation_planning', description: 'See the salary-review rows assigned to me as planner in an open cycle — never anyone else\'s' },
  { code: PERMISSIONS.COMP_PLAN_PLAN, module: 'compensation_planning', description: 'Enter and submit proposed base salaries for the rows assigned to me as planner' },
  { code: PERMISSIONS.COMP_PLAN_REVIEW, module: 'compensation_planning', description: 'HR review of every proposal in a cycle (organization-wide scope): return, change with a reason, approve' },
  { code: PERMISSIONS.COMP_PLAN_MANAGE_CYCLES, module: 'compensation_planning', description: 'Create salary-review cycles, set the population, activate, reassign planners, start review, archive' },
  { code: PERMISSIONS.COMP_PLAN_MANAGE_BUDGET, module: 'compensation_planning', description: 'Set the base-salary increase budget of a cycle' },
  { code: PERMISSIONS.COMP_PLAN_FINALIZE, module: 'compensation_planning', description: 'Finalize a reviewed cycle (freezes the approved plan; changes no salary)' },
  { code: PERMISSIONS.COMP_PLAN_APPLY, module: 'compensation_planning', description: 'Apply a finalized cycle to salary history (also needs payroll.manage, the authority over compensation itself)' },
  { code: PERMISSIONS.COMP_PLAN_VIEW_REPORTS, module: 'compensation_planning', description: 'Aggregate salary-review reporting: population, completion, budget and increase totals — never a person' },
];

/**
 * Permissions the SYSTEM_ADMIN role can never lose (guards against locking every admin out).
 * Enforced by PATCH /roles/:id/permissions; the UI locks these checkboxes for SYSTEM_ADMIN.
 */
export const CRITICAL_PERMISSIONS: PermissionCode[] = [
  PERMISSIONS.USERS_VIEW,
  PERMISSIONS.USERS_CREATE,
  PERMISSIONS.USERS_UPDATE,
  PERMISSIONS.USERS_ACTIVATE,
  PERMISSIONS.ROLES_VIEW,
  PERMISSIONS.ROLES_MANAGE,
];

/** Human labels for the action part of a permission code, used by the Roles UI. */
export const PERMISSION_ACTION_LABELS: Record<string, string> = {
  view: 'View',
  create: 'Create',
  update: 'Update',
  activate: 'Activate / Deactivate',
  manage: 'Manage',
  clock: 'Clock in / out',
  request: 'Request',
  manage_policy: 'Manage policies',
  view_own: 'View own',
  run: 'Run',
  approve: 'Approve',
  correct: 'Correct',
  schedule_manage: 'Manage schedules',
};
