import { addDays, type ReportTemplateDto } from '@hr/shared';

/**
 * Application-owned starting points. Every column is one the dataset already offers; there is nothing privileged here.
 * Task 53: built per request from the reference organization's business `today` (it was the server's UTC date, frozen
 * at process start).
 */
export const reportTemplates = (today: string): ReportTemplateDto[] => [
  { id: 'employee-directory', name: 'Employee directory', description: 'Active employees with organization, department, job and position.', datasetId: 'employee_directory', definition: { columns: ['employeeCode', 'firstName', 'lastName', 'department', 'job', 'position', 'employmentType', 'hireDate'], filters: [{ fieldId: 'employmentStatus', operator: 'EQ', value: 'ACTIVE' }], sort: [{ fieldId: 'employeeCode', direction: 'ASC' }], groupBy: [], aggregations: [], pageSize: 50 } },
  { id: 'headcount-by-department', name: 'Headcount by department', description: 'Active employees counted per department.', datasetId: 'headcount_summary', definition: { columns: ['department'], filters: [{ fieldId: 'employmentStatus', operator: 'EQ', value: 'ACTIVE' }], sort: [], groupBy: ['department'], aggregations: [{ fieldId: 'employees', function: 'COUNT', alias: 'Employees' }], pageSize: 50 } },
  { id: 'leave-summary', name: 'Leave summary', description: 'Approved leave units by department and leave type for the current year.', datasetId: 'leave_requests', definition: { columns: ['department', 'leaveType'], filters: [{ fieldId: 'status', operator: 'EQ', value: 'APPROVED' }, { fieldId: 'startDate', operator: 'BETWEEN', value: [`${today.slice(0, 4)}-01-01`, `${today.slice(0, 4)}-12-31`] }], sort: [], groupBy: ['department', 'leaveType'], aggregations: [{ fieldId: 'units', function: 'SUM', alias: 'Approved units' }, { fieldId: 'units', function: 'COUNT', alias: 'Requests' }], pageSize: 50 } },
  { id: 'attendance-summary', name: 'Attendance summary', description: 'Days by attendance status per employee for the current month.', datasetId: 'attendance_summary', definition: { columns: ['employeeCode', 'status'], filters: [{ fieldId: 'attendanceDate', operator: 'BETWEEN', value: [`${today.slice(0, 7)}-01`, today] }], sort: [], groupBy: ['employeeCode', 'status'], aggregations: [{ fieldId: 'workMinutes', function: 'COUNT', alias: 'Days' }, { fieldId: 'workMinutes', function: 'SUM', alias: 'Worked minutes' }], pageSize: 50 } },
  { id: 'performance-results', name: 'Performance results', description: 'Finalized weighted scores and ratings by cycle.', datasetId: 'performance_results', definition: { columns: ['cycle', 'employeeCode', 'employeeName', 'department', 'weightedScore', 'rating', 'finalizedAt'], filters: [], sort: [{ fieldId: 'finalizedAt', direction: 'DESC' }], groupBy: [], aggregations: [], pageSize: 50 } },
  { id: 'competency-gap', name: 'Competency gaps', description: 'Employees below a required level on their current job profile. Not-assessed rows are excluded on purpose.', datasetId: 'competency_gaps', definition: { columns: ['employeeCode', 'employeeName', 'department', 'competency', 'currentLevel', 'requiredLevel', 'gapNeeded'], filters: [{ fieldId: 'status', operator: 'EQ', value: 'GAP' }], sort: [{ fieldId: 'gapNeeded', direction: 'DESC' }], groupBy: [], aggregations: [], pageSize: 50 } },
  { id: 'training-completion', name: 'Training completion', description: 'Enrolments by course and status.', datasetId: 'training_history', definition: { columns: ['status'], filters: [], sort: [], groupBy: ['status'], aggregations: [{ fieldId: 'enrolledAt', function: 'COUNT', alias: 'Enrolments' }], pageSize: 50 } },
  { id: 'recruitment-funnel', name: 'Recruitment funnel', description: 'Applications by stage over the last twelve months.', datasetId: 'recruitment_applications', definition: { columns: ['stage'], filters: [{ fieldId: 'appliedAt', operator: 'BETWEEN', value: [addDays(today, -365), today] }], sort: [], groupBy: ['stage'], aggregations: [{ fieldId: 'applicationNumber', function: 'COUNT', alias: 'Applications' }], pageSize: 50 } },
];
